### ISSUE TITLE
No working build instructions

### ISSUE THREAD

**Issue by krystian-hebel** [fobnail/docs#34]
Build instructions used to be located in https://github.com/fobnail/docs/blob/main/docs/environment.md, but it is now outdated. It also doesn't say how other components (Platform Owner, Attester) can be build and used.

**Comment by krystian-hebel** [comment]
@pietrushnic are instructions from recently merged #47 enough to close this issue in your opinion?

**Comment by pietrushnic** [comment]
@krystian-hebel, yes, I think it is enough.
